#!/usr/bin/env python3
"""Deliberation: for each candidate T-state, predict BDI outcome + reward, then pick best_action."""

import argparse
import json
import sys
from pathlib import Path
from openai import OpenAI
from action_space_v2 import enrich_action_payload, enrich_labeled_record

try:
    from dotenv import load_dotenv
except ModuleNotFoundError:
    def load_dotenv() -> None:
        return None


load_dotenv()

REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFEST_DIR = REPO_ROOT / "data" / "manifest"
LABELED_DIR = REPO_ROOT / "data" / "labeled"

DEFAULT_ALPHA = 0.4
DEFAULT_BETA = 0.5
DEFAULT_GAMMA = 0.1
MAX_RETRIES = 2

SILENCE_STATE = "T1_SILENT_OBSERVE"
STAGE_ORDER = {"attention": 0, "interest": 1, "desire": 2, "action": 3}

# ── T-state definitions ────────────────────────────────────────────────────────

# Fixed intervention cost per T-state — not generated by model
T_STATE_COSTS = {
    "T1_SILENT_OBSERVE":     0.00,
    "T2_VALUE_COMPARE":      0.30,
    "T3_STRONG_RECOMMEND":   0.65,
    "T4_OPEN_QUESTION":      0.20,
    "T5_DEMO":               0.40,
    "T6_ACK_WAIT":           0.10,
    "T7_DISENGAGE":          0.05,
    "T_TRANSACT":            0.00,
}

# What each T-state concretely does — injected into expert prompt
T_STATE_DESCRIPTIONS = {
    "T1_SILENT_OBSERVE":
        "静默观察（不打扰）— 屏幕保持极简 attract，不弹建议；数字人静默。"
        "顾客感受：自主空间，零压力。action_cost=0.00",
    "T2_VALUE_COMPARE":
        "弹出对比卡 — 屏幕弹出双卡对比（价格/规格/适用场景），无强 CTA；"
        "数字人说「我把这两款的差别帮您列清楚」。"
        "顾客感受：信息变清晰，选择成本降低。action_cost=0.30",
    "T3_STRONG_RECOMMEND":
        "强推荐单品 — 单品全屏卡 + 「立即购买」CTA；"
        "数字人说「这款最适合您，建议直接选这款」。"
        "顾客感受：明确引导，推销感较强。action_cost=0.65",
    "T4_OPEN_QUESTION":
        "开放式提问 — 三选一气泡题（功能/价格/场景）；"
        "数字人说「您今天想先看哪一点？」+ 留白 1.5s。"
        "顾客感受：被邀请参与，主动感强。action_cost=0.20",
    "T5_DEMO":
        "短演示/3D 动画 — 关键功能 3D 动画（≤10s 一个细节）；数字人 5–8s 解说。"
        "顾客感受：直观了解功能亮点，有一定注意力占用。action_cost=0.40",
    "T6_ACK_WAIT":
        "轻确认后等待 — 屏幕显示「为您保留中，需要随时叫我」小窗；"
        "数字人「您慢慢看」后退至背景。"
        "顾客感受：压力消除，被体贴。action_cost=0.10",
    "T7_DISENGAGE":
        "主动退出互动 — 回到 attract loop；数字人「不打扰您了」后静默。"
        "顾客感受：被放手，无追销感。action_cost=0.05",
    "T_TRANSACT":
        "收银/出货 — 订单确认页 + 数字人结尾致谢；取货门开/出货口出货。"
        "顾客感受：顺畅完成购买。action_cost=0.00",
}

# Fixed 4 candidates per AIDA stage — T1 always first as no-intervention baseline
AIDA_CANDIDATES = {
    "attention": ["T1_SILENT_OBSERVE", "T4_OPEN_QUESTION", "T5_DEMO",            "T7_DISENGAGE"],
    "interest":  ["T1_SILENT_OBSERVE", "T2_VALUE_COMPARE", "T4_OPEN_QUESTION",   "T5_DEMO"],
    "desire":    ["T1_SILENT_OBSERVE", "T2_VALUE_COMPARE", "T3_STRONG_RECOMMEND", "T6_ACK_WAIT"],
    "action":    ["T1_SILENT_OBSERVE", "T6_ACK_WAIT",      "T7_DISENGAGE",        "T_TRANSACT"],
}

# ── Prompt ────────────────────────────────────────────────────────────────────

EXPERT_PROMPT = """你是一个 BDI 认知建模 + 零售行为领域的专家标注员，对 AIDA 购买阶段理论和顾客心理状态迁移有深入理解。

# 背景
智能零售设备（售货机/智能冰箱）内置摄像头持续观察顾客，可以主动切换到不同的机器状态（T-state）来与顾客互动。
你的任务：针对当前顾客状态，对下方 {n} 个候选 T-state 逐一推理 ActionOutcome。

注意：T-state 只是兼容标签。当前语义中心是 6 个 DialogueAct：
Greet / Elicit / Inform / Recommend / Reassure / Hold。
脚本会在输出后自动补齐 dialogue_act、act_params.supporting_acts 和 terminal_realization。
旧 co_acts 只作为兼容输入；新输出如需回溯旧格式，使用 legacy_co_acts。

# 候选 T-state 定义（含固定介入成本）
{tstate_descriptions}

# 推理方法（每个候选都走完整链路，先推理再填字段）

1. **BDI 因果链**：该 T-state 的具体行为（屏幕内容、数字人语音）会更新顾客哪个 belief？
   激活还是抑制哪个 desire？intention 会更靠近购买还是后退/放弃？

2. **AIDA 迁移**：基于 BDI 变化推断 next_aida_stage。
   阶段推进需要信念更新 + 欲望强化 + 意图落地，缺一不可。

3. **风险评估**：当前顾客处于 {aida_stage} 阶段，这个 T-state 是否时机合适？
   顾客会感到被打扰、被推销、还是被理解？给出 risk / benefit。

4. **量化**（数值说明）：
   - delta_stage：AIDA 推进量（推进一格 ≈ +0.33，倒退为负，不变 ≈ 0）
   - delta_mental：兴趣升降 + 犹豫升降 + 信任升降的综合量（范围 -3 ~ +3，正=改善）
   - ⚠️ action_cost 由系统根据 T-state 固定注入，**你不需要生成此字段**

5. **rationale**：把整条推理链压缩为一句话因果解释

# 一致性约束（输出必须满足）
- next_bdi.intention 必须与 next_aida_stage 语义一致
  （action 阶段的 intention 应是"准备操作/购买"而非"想再看看"）
- risk=high 时 delta_mental 通常为负（顾客反感）
- benefit=high 时 delta_mental 不应明显为负
- T1_SILENT_OBSERVE 的 delta_stage 应在 [-0.1, 0.3]（沉默不能大幅改变阶段）
- {n} 个候选的最终 reward 之差应 ≥ 0.25（需有足够区分度）

# 顾客 Manifest
{manifest_json}

# 当前候选 T-state（AIDA 阶段：{aida_stage}）
{candidate_list}

# 输出格式
只输出 JSON，不附加解释或 Markdown：
{{
  "outcomes": {{
    "T1_SILENT_OBSERVE": {{
      "next_aida_stage": "...",
      "next_bdi": {{"belief": "...", "desire": "...", "intention": "..."}},
      "risk": "low",
      "benefit": "low",
      "delta_stage": 0.0,
      "delta_mental": 0.0,
      "rationale": "..."
    }},
    "<second_state>": {{ "..." }},
    "<third_state>":  {{ "..." }},
    "<fourth_state>": {{ "..." }}
  }}
}}"""

RETRY_PROMPT = """上一轮输出存在以下一致性问题，请根据推理规则逐条修正后重新输出完整 JSON：

{errors}

只输出修正后的 JSON，不附加解释。"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def get_candidates(aida_stage: str) -> list[str]:
    return AIDA_CANDIDATES.get(aida_stage, AIDA_CANDIDATES["interest"])


def build_tstate_descriptions(candidates: list[str]) -> str:
    lines = []
    for t in candidates:
        desc = T_STATE_DESCRIPTIONS.get(t, t)
        lines.append(f"- **{t}**：{desc}")
    return "\n".join(lines)


def build_candidate_list(candidates: list[str]) -> str:
    return "\n".join(f"{i+1}. {t}" for i, t in enumerate(candidates))


# ── Validation ────────────────────────────────────────────────────────────────

def validate_outcomes(current_aida: str, candidates: list[str], outcomes: dict) -> list[str]:
    errors = []
    current_idx = STAGE_ORDER.get(current_aida, -1)

    # Check all expected candidates are present
    for t in candidates:
        if t not in outcomes:
            errors.append(f"缺少候选 T-state 的 outcome：{t}")

    for state, oc in outcomes.items():
        next_stage = oc.get("next_aida_stage", "")
        next_idx = STAGE_ORDER.get(next_stage, -1)
        ds = float(oc.get("delta_stage", 0))
        dm = float(oc.get("delta_mental", 0))
        risk = oc.get("risk", "")
        benefit = oc.get("benefit", "")
        intention = oc.get("next_bdi", {}).get("intention", "")

        # delta_stage direction must match stage transition
        stage_delta = next_idx - current_idx
        if stage_delta > 0 and ds < -0.05:
            errors.append(
                f"[{state}] 阶段推进 {current_aida}→{next_stage} 但 delta_stage={ds:.2f} 为负"
            )
        elif stage_delta < 0 and ds > 0.05:
            errors.append(
                f"[{state}] 阶段倒退 {current_aida}→{next_stage} 但 delta_stage={ds:.2f} 为正"
            )

        # risk=high implies negative delta_mental
        if risk == "high" and dm > 0.3:
            errors.append(
                f"[{state}] risk=high 但 delta_mental={dm:.2f} 为正——高风险动作不应改善心理状态"
            )

        # benefit=high implies positive delta_mental
        if benefit == "high" and dm < -0.5:
            errors.append(
                f"[{state}] benefit=high 但 delta_mental={dm:.2f} 明显为负——矛盾"
            )

        # action stage intention must not express hesitation
        HESITATION_WORDS = ["再看", "再想", "考虑", "不确定", "犹豫", "不太确定"]
        if next_stage == "action" and any(w in intention for w in HESITATION_WORDS):
            errors.append(
                f"[{state}] next_aida_stage=action 但 intention 仍含犹豫语义：「{intention}」"
            )

        # T1 baseline should not cause large stage shifts
        if state == SILENCE_STATE and abs(ds) > 0.4:
            errors.append(
                f"[{SILENCE_STATE}] delta_stage={ds:.2f} 幅度过大，沉默基线不应大幅改变顾客阶段"
            )

    # Reward spread must be sufficient
    rewards = []
    for state, oc in outcomes.items():
        cost = T_STATE_COSTS.get(state, 0.0)
        ds = float(oc.get("delta_stage", 0))
        dm = float(oc.get("delta_mental", 0))
        r = compute_reward(ds, dm, cost, DEFAULT_ALPHA, DEFAULT_BETA, DEFAULT_GAMMA)
        rewards.append(r)

    if len(rewards) > 1 and max(rewards) - min(rewards) < 0.25:
        r_str = ", ".join(f"{r:.2f}" for r in rewards)
        errors.append(
            f"Reward 分布过于集中 [{r_str}]，候选之间缺乏区分度，请拉大 delta_stage / delta_mental 的差距"
        )

    return errors


# ── Core ──────────────────────────────────────────────────────────────────────

def compute_reward(ds: float, dm: float, cost: float,
                   alpha: float, beta: float, gamma: float) -> float:
    return max(-1.0, min(1.0, alpha * ds + beta * dm - gamma * cost))


def attach_costs_and_rewards(outcomes: dict, alpha: float, beta: float, gamma: float) -> None:
    """Inject fixed cost/reward and v2 action/realization fields."""
    for state, oc in outcomes.items():
        cost = T_STATE_COSTS.get(state, 0.0)
        oc["action_cost"] = cost
        oc["reward"] = compute_reward(
            float(oc.get("delta_stage", 0)),
            float(oc.get("delta_mental", 0)),
            cost, alpha, beta, gamma,
        )
        oc.update(enrich_action_payload(state))


def deliberate(
    manifest: dict,
    alpha: float = DEFAULT_ALPHA,
    beta: float = DEFAULT_BETA,
    gamma: float = DEFAULT_GAMMA,
    model: str = "gpt-5.5",
) -> dict:
    client = OpenAI()
    current_aida = manifest.get("aida_stage", "interest")
    candidates = get_candidates(current_aida)

    prompt = EXPERT_PROMPT.format(
        n=len(candidates),
        aida_stage=current_aida,
        tstate_descriptions=build_tstate_descriptions(candidates),
        candidate_list=build_candidate_list(candidates),
        manifest_json=json.dumps(manifest, ensure_ascii=False, indent=2),
    )

    messages = [{"role": "user", "content": prompt}]
    last_outcomes = None

    for attempt in range(MAX_RETRIES + 1):
        response = client.chat.completions.create(
            model=model,
            messages=messages,
            response_format={"type": "json_object"},
        )
        raw_content = response.choices[0].message.content
        outcomes = json.loads(raw_content)["outcomes"]

        attach_costs_and_rewards(outcomes, alpha, beta, gamma)
        errors = validate_outcomes(current_aida, candidates, outcomes)
        last_outcomes = outcomes

        if not errors:
            break

        if attempt < MAX_RETRIES:
            error_text = "\n".join(f"- {e}" for e in errors)
            print(f"[deliberate] attempt {attempt+1} failed ({len(errors)} errors), retrying…",
                  file=sys.stderr)
            messages.append({"role": "assistant", "content": raw_content})
            messages.append({"role": "user", "content": RETRY_PROMPT.format(errors=error_text)})
        else:
            print(f"[deliberate] validation still failing after {MAX_RETRIES} retries, using best attempt",
                  file=sys.stderr)
            for e in errors:
                print(f"  ! {e}", file=sys.stderr)

    best_action = max(last_outcomes.items(), key=lambda kv: kv[1]["reward"])[0]
    best_payload = enrich_action_payload(best_action)

    record = {
        "candidate_actions": candidates,
        "outcomes": last_outcomes,
        "best_action": best_action,
        "dialogue_act": best_payload["dialogue_act"],
        "act_params": best_payload["act_params"],
        **({"legacy_co_acts": best_payload["legacy_co_acts"]} if best_payload.get("legacy_co_acts") else {}),
        "realization": best_payload["terminal_realization"],
        "reward_weights": {"alpha": alpha, "beta": beta, "gamma": gamma},
    }
    return enrich_labeled_record(record)


# ── CLI ───────────────────────────────────────────────────────────────────────

def find_missing_labeled() -> list[Path]:
    return [
        f for f in sorted(MANIFEST_DIR.glob("piwm_*.json"))
        if not (LABELED_DIR / f.name).exists()
    ]


def main():
    parser = argparse.ArgumentParser(
        description="Deliberation: predict outcome per candidate T-state, pick best_action. "
                    "Run without arguments to batch-process all un-labeled manifests."
    )
    parser.add_argument(
        "manifest", nargs="?",
        help="Manifest JSON path (use - for stdin). Omit to batch all data/manifest/ → data/labeled/."
    )
    parser.add_argument("--model", default="gpt-5.5")
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA)
    parser.add_argument("--beta",  type=float, default=DEFAULT_BETA)
    parser.add_argument("--gamma", type=float, default=DEFAULT_GAMMA)
    parser.add_argument("--no-merge", action="store_true", help="Output only deliberation fields")
    parser.add_argument("--dry-run", action="store_true",
                        help="Single file: print prompt. Batch: list files that would be processed.")
    parser.add_argument("-o", "--output",
                        help=f"Output path (single-file mode only). Default: {LABELED_DIR}/<id>.json. Use '-' for stdout.")
    args = parser.parse_args()

    # ── batch mode ──
    if args.manifest is None:
        pending = find_missing_labeled()
        if not pending:
            print("All manifests already labeled.", file=sys.stderr)
            return
        print(f"{'[dry-run] would process' if args.dry_run else 'Processing'} "
              f"{len(pending)} file(s):", file=sys.stderr)
        for f in pending:
            print(f"  {f.name}", file=sys.stderr)
        if args.dry_run:
            return
        for f in pending:
            manifest = json.loads(f.read_text(encoding="utf-8"))
            result = deliberate(manifest, alpha=args.alpha, beta=args.beta,
                                gamma=args.gamma, model=args.model)
            output = result if args.no_merge else {**manifest, **result}
            out_path = LABELED_DIR / f.name
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
            print(f"  ✓ {out_path.name}", file=sys.stderr)
        return

    # ── single-file mode ──
    if args.manifest == "-":
        manifest = json.load(sys.stdin)
    else:
        with open(args.manifest, "r", encoding="utf-8") as f:
            manifest = json.load(f)

    if args.dry_run:
        current_aida = manifest.get("aida_stage", "interest")
        candidates = get_candidates(current_aida)
        print(EXPERT_PROMPT.format(
            n=len(candidates),
            aida_stage=current_aida,
            tstate_descriptions=build_tstate_descriptions(candidates),
            candidate_list=build_candidate_list(candidates),
            manifest_json=json.dumps(manifest, ensure_ascii=False, indent=2),
        ))
        return

    result = deliberate(manifest, alpha=args.alpha, beta=args.beta,
                        gamma=args.gamma, model=args.model)
    output = result if args.no_merge else {**manifest, **result}
    out = json.dumps(output, ensure_ascii=False, indent=2)

    if args.output == "-":
        print(out)
        return

    out_path = (Path(args.output) if args.output
                else LABELED_DIR / f"{manifest.get('session_id', 'unknown')}.json")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out, encoding="utf-8")
    print(f"Saved to {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
